project:
  type: website
  output-dir: "."

website:
  title: "JOSHUA IRIZARRY"
  navbar:
    pinned: true
    left:
      - text: Project
        href: quarto-template.qmd
      - text: Blog
        href: blog-listing.qmd
  page-footer: 
    center: "Powered with GitHub and Quarto<br>Â© Joshua Irizarry, 2023"

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    mainfont: system-ui; 
    highlight-style: atom-one
    css: styles.css
    toc: false
    include-after-body: target_blank.html
    
